sudo: required
language: node_js
node_js:
  - "5"
  - "6"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


script:
  - yarn lint
  - yarn test
  - yarn build

after_success:
  - yarn codecov
